apiVersion: v1
kind: Service
metadata:
  name: tan-dara5304-nexttt-js-service
spec:
  type: NodePort
  selector:
    app: tan-dara5304-nexttt-js
  ports:
    - protocol: TCP
      port: 8314
      targetPort: 3000
